name-template: 'CodeWalker-Dabz-v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 New Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '⬆️ Dependencies'
    labels:
      - 'dependencies'
    collapse-after: 3

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
  default: patch

template: |
  ## What's Changed in CodeWalker

  $CHANGES

  ## Contributors
  
  $CONTRIBUTORS

exclude-labels:
  - 'skip-changelog'
  - 'wip'

autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
      - 'docs/**/*'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
  - label: 'chore'
    files:
      - '.github/**/*'
      - '*.yml'
      - '*.yaml'